name: Publish to PyPI
on:
  release:
    types: [published]

jobs:
  pypi_release:
    name: Builds Using Poetry and Publishes to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN_GITHUB_SII }}